#!/bin/sh

git add .

if [ $# -eq 0 ]
    then
        note=
        echo -n 'Commit note? '
        read note
        git commit -m \""$note"\"
    else
        git commit -m \""$1"\"
fi

git push -u origin master
cd ..
zip -r -u -b Thesis thesis.zip
cd Thesis
